# @see: https://github.com/netlify/netlify-cms/blob/master/docs/quick-start.md

backend:
  name: github
  repo: beetwo/website
  branch: production

# publish_mode: editorial_workflow
media_folder: "source/assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "projects" # Used in routes, e.g. /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "source/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}.html" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Layout",         name: "layout",     widget: "hidden",   default: "project_layout"}
      - {label: "Title",          name: "title",      widget: "string" }
      - {label: "Tagline",        name: "tagline",    widget: "markdown" }
      - {label: "Title Image",    name: "titleimage", widget: "image" }
      - {label: "Body Image 1",   name: "image0",     widget: "image", required: false }
      - {label: "Body Image 2",   name: "image1",     widget: "image", required: false }
      - {label: "Body Image 3",   name: "image2",     widget: "image", required: false }
      - {label: "Body Image 4",   name: "image3",     widget: "image", required: false }
      - {label: "Body",           name: "body",       widget: "markdown" }
      - {label: "Publish Date",   name: "date",       widget: "datetime" }

  - name: "team"
    label: "Team"
    folder: "source/team"
    create: true
    slug: "{{slug}}.html"
    fields:
      - {label: "Layout",         name: "layout",     widget: "hidden",   default: "team_layout"}
      - {label: "Title",          name: "title",      widget: "string" }
      - {label: "Publish Date",   name: "date",       widget: "datetime" }
      - {label: "Featured Image", name: "thumbnail",  widget: "image" }
      - {label: "Email",           name: "email",       widget: "string" }
      - {label: "Body",           name: "body",       widget: "markdown" }
      

  - name: "texts"
    label: "Texts"
    folder: "source/texts"
    create: true
    slug: "{{slug}}.html"
    fields:
      - {label: "Title",          name: "title",      widget: "string" }
      - {label: "Body",           name: "body",       widget: "markdown" }