# @see: https://github.com/netlify/netlify-cms/blob/master/docs/quick-start.md

backend:
  name: github
  repo: beetwo/website
  branch: production

# publish_mode: editorial_workflow
media_folder: "source/assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "projects" # Used in routes, e.g. /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "source/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}.html" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Layout",         name: "layout",     widget: "hidden",   default: "project_layout"}
      - {label: "Title",          name: "title",      widget: "string" }
      - {label: "Publish Date",   name: "date",       widget: "datetime" }
      - {label: "Featured Image", name: "thumbnail",  widget: "image" }
      - {label: "Body",           name: "body",       widget: "markdown" }

  - name: "team" # Used in routes, e.g. /admin/collections/blog
    label: "Team" # Used in the UI
    folder: "source/team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}.html" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Layout",         name: "layout",     widget: "hidden",   default: "team_layout"}
      - {label: "Title",          name: "title",      widget: "string" }
      - {label: "Publish Date",   name: "date",       widget: "datetime" }
      - {label: "Featured Image", name: "thumbnail",  widget: "image" }
      - {label: "Body",           name: "body",       widget: "markdown" }